const STORAGE_CLASS = {
  STANDARD: 'STANDARD',
  STANDARD_IA: 'STANDARD_IA',
  ONEZONE_IA: 'ONEZONE_IA',
  INTELLIGENT_TIERING: 'INTELLIGENT_TIERING',
  GLACIER: 'GLACIER',
  DEEP_ARCHIVE: 'DEEP_ARCHIVE',
}

export type STORAGE_CLASS = typeof STORAGE_CLASS[keyof typeof STORAGE_CLASS]
